Chat/urls.py
from django.urls import path
from . import views as v

app_name = 'chat'

urlpatterns = [
    path('', v.ChatListView.as_view(), name='all'),
    path('new/', v.ChatCreateView.as_view(), name='new'),
]

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
	url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), 
		name='login'),
	url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
	url(r'^signup/$', views.Signup.as_view(), name='signup'),
]


chatApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from accounts import urls as accounts_urls
from . import views
from . import views as base_views

urlpatterns = [
    path('', base_views.HomePage.as_view(), name='home'),
    path('accounts/', include(accounts_urls)),
    path('detection/', views.DETECTION_PAGE, name='detection'),
    path('info/', views.info, name='info'),
    path('classifier/predict/', views.classifier, name='predict'),
    path('classifier/', views.classifier, name='classifier')

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

Chat/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from django.urls import reverse


# Create your models here.
User = get_user_model()

class INPUT_IMAGES(models.Model): 
    Input_image = models.ImageField(upload_to='static/images/') 

accounts/models.py
from django.db import models
from django.contrib import auth


# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

	def __str__(self):
		return f"{self.username}"

Chat/forms.py
from django import forms
from .models import INPUT_IMAGES


class INPUT_IMAGE_FORM(forms.ModelForm):   
    class Meta: 
        model = INPUT_IMAGES
        fields = ['Input_image'] 

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
	fields = ("username", "password1", "password2")
	model = get_user_model()

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['username'].help_text = None		
		self.fields['password1'].help_text = None
		self.fields['password2'].help_text = None

Chat/views.py
from django.views.generic import CreateView, ListView
from .forms import ChatForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Chat
from django.utils import timezone

from django.http import HttpResponse 
from django.shortcuts import render, redirect 
from .forms import *


from django import template


# Create your views here.


class ChatCreateView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:login'
    form_class = ChatForm
    model = Chat

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class ChatListView(LoginRequiredMixin, ListView):
    model = Chat

    def get_queryset(self):
        return Chat.objects.filter(posted_at__lte=timezone.now()).order_by('posted_at')


accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .forms import UserCreateForm
from django.views.generic import CreateView

# Create your views here.
class Signup(CreateView):
	form_class = UserCreateForm
	success_url = reverse_lazy('accounts:login')
	template_name = 'accounts/signup.html'

chatApp/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'


def info(request):
    return render(request, 'info.html')


def DETECTION_PAGE(request):
    return render(request, 'detection.html')


from django.shortcuts import render
import numpy as np
import joblib

model = joblib.load("fraud_detection_model.sav")


def classifier(request):
    global features
    if request.method == "POST":
        # Get the form data and convert to a NumPy array
        feature1 = request.POST.get('feature1')
        feature2 = request.POST.get('feature1')
        feature3 = request.POST.get('feature1')
        feature4 = request.POST.get('feature1')
        feature5 = request.POST.get('feature1')
        feature6 = request.POST.get('feature1')
        feature7 = request.POST.get('feature1')
        feature8 = request.POST.get('feature1')
        feature9 = request.POST.get('feature1')
        feature10 = request.POST.get('feature1')
        feature11 = request.POST.get('feature1')
        feature12 = request.POST.get('feature1')
        feature13 = request.POST.get('feature1')
        feature14 = request.POST.get('feature1')
        feature15 = request.POST.get('feature1')
        feature16 = request.POST.get('feature1')
        feature17 = request.POST.get('feature1')
        feature18 = request.POST.get('feature1')
        feature19 = request.POST.get('feature1')
        feature20 = request.POST.get('feature1')
        feature21 = request.POST.get('feature1')
        feature22 = request.POST.get('feature1')
        feature23 = request.POST.get('feature1')
        feature24 = request.POST.get('feature1')
        feature25 = request.POST.get('feature1')
        feature26 = request.POST.get('feature1')
        feature27 = request.POST.get('feature1')
        feature28 = request.POST.get('feature1')
        feature29 = request.POST.get('feature1')

        # Add more features here as needed...

        # Create a feature array
        features = np.array(
            [feature1, feature2, feature3, feature4, feature5, feature6, feature7, feature8, feature9, feature10,
             feature11, feature12, feature13, feature14, feature15, feature16, feature17, feature18, feature19,
             feature20, feature21, feature22, feature23, feature24, feature25, feature26, feature27, feature28,
             feature29]).reshape(1, -1)

        # Make a prediction using the model
        prediction = model.predict(features)

        if prediction == 1:
            return render(request, "fraudulent.html")
        else:
            return render(request, "not_fraudulent.html")
    else:
        return render(request, "classifier.html")


def predict(request):
    return render(request, 'classifier.py')

templates/Chat/chat_form.html
{% extends "base.html" %}

{% block content %}
    <form method="POST">
    	{% csrf_token %}
    	{{ form.as_p }}

    	<br><input type="submit" value="Post" class="btn btn-lg btn-outline-primary">
    </form>
{% endblock content %}


templates/Chat/chat_list.html
{% extends "base.html" %}

{% block title %}
    Chatting
{% endblock title %}

{% block content %}
    <a href="/chat"><button class="btn btn btn-primary"><i class="fa fa-refresh" aria-hidden="true"></i>
    Rerfresh For Any New Chats</button></a><br><br><br>

    {% for chat in object_list %}

    		{% if chat.user.is_superuser  %}                    
                {% if  user.get_username == chat.receiver  %}
            	    <div class="chat" style="width: 90%; background: rgb(127, 140, 80); box-shadow: 2px 0px 25px 20px #330;">    		    
    		            <small class="chat-user-special"> {{ chat.user }}  -> {{ chat.receiver }}      </small>
    		            <p><b class="chat-content">{{ chat|linebreaks }} </b></p>
    		            <small class="chat-date">{{ chat.posted_at }}</small>
            	    </div><br><br>    
                {% endif %}
    		
    		{% else %}
                {% if  user  ==  chat.user  and chat.receiver == 'admin' %}
                	<div class="chat" style="width: 90%; background: rgb(50, 40, 127); box-shadow: 2px 0px 25px 20px #000;text-align: right;">
    			    <small class="chat-user"> {{ chat.user }}  -> {{ chat.receiver }}  </small>    		    
    		        <p><b class="chat-content">{{ chat|linebreaks }}</b></p>
    		        <small class="chat-date">{{ chat.posted_at }}</small>
            		</div><br><br>    
                {% endif %}
    		{% endif %}

            {% if user.get_username == 'admin'%}
                        {% if  chat.user.get_username == 'admin'  %}
            	            <div class="chat" style="width: 90%; background: rgb(50, 40, 127); box-shadow: 2px 0px 25px 20px #330;text-align: right;">    		    
    		                    <small class="chat-user-special"> {{ chat.user }}  -> {{ chat.receiver }}      </small>
    		                    <p><b class="chat-content">{{ chat|linebreaks }} </b></p>
    		                    <small class="chat-date">{{ chat.posted_at }}</small>
            	            </div><br><br>    
                        {% endif %}
    		
                        {% if  chat.receiver == 'admin' %}
                	        <div class="chat" style="width: 90%; background: rgb(127, 140, 80); box-shadow: 2px 0px 25px 20px #000;">
    			            <small class="chat-user"> {{ chat.user }}  -> {{ chat.receiver }}  </small>    		    
    		                <p><b class="chat-content">{{ chat|linebreaks }}</b></p>
    		                <small class="chat-date">{{ chat.posted_at }}</small>
            		        </div><br><br>    
                        {% endif %}
            {% endif %}
    		

    {% empty %}
    <h1 class="heading">No Chats Yet Be The First To Message!</h1><br>

    {% endfor %}
    <br><a href="{% url 'chat:new' %}"><button class="btn btn-outline-primary">New Message</button></a>
{% endblock content %}

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}
    Login Portal
{% endblock title %}


{% block content %}

		<div class="row">
			<div class="col-md-4">
				<form method="POST">
					{% csrf_token %}
					{{ form.as_p }}

					<input type="submit" value='Login' class="btn btn-outline-primary">
				</form>
			</div>

			<div class="col-md-7">
				<h4>Welcome Back to system!</h4><hr>
				<p class="description">
					Just to ensure your security please login.

				</p>
			</div>
		</div>
{% endblock content %}

templates/accounts/signup.html
{% extends "base.html" %}
{% block title %}

    Signup Portal

{% endblock title %}

{% block content %}
    <div class="row">
			<div class="col-md-4">
				<form method="POST">
					{% csrf_token %}
					{{ form.as_p }}

					<input type="submit" value='Signup' class="btn btn-outline-primary">
				</form>
			</div>
			<div class="col-md-7">
				<h4>Be Ready To Become a Part Of System</h4><hr>
				<p class="description">
					Well, Hello and welcome to the System! 
				</p>
			</div>
		</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

		
		<!-- Title -->
		<title>{% block title %} {% endblock title %}</title>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
		
		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Poppins:wght@300;400;500;600;700;800;900&family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">
		
		<!-- Style sheet -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
		<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

		<!-- Favicon -->
		<!-- <link rel="shortcut icon" type="image/svg" href="{% static 'favicon.svg' %}"> -->

		<!-- <link rel="icon" type="image/png"  href="{% static 'todo/logo.png' %}"> -->
		<!-- <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> -->
		<link rel="icon" type="image/png"  href="{% static 'logo.png' %}">

</head>

<body >

		<!-- Nav -->
		<!-- <nav class="navbar navbar sticky-top navbar-expand-lg navbar-dark" style="font-weight: 300; box-shadow: 0px 0px 5px px #000; font-family: 'Ubuntu', sans-serif;"> -->

			<nav class="navbar navbar sticky-top navbar-expand-lg navbar-dark" style="background-color:  #7e641f; font-weight: 300; box-shadow: 0px 0px 20px 5px rgb(172, 138, 27); font-family: 'Ubuntu', sans-serif;">
				{% if user.is_authenticated %}
				<a class="navbar-brand" href="{% url 'home' %}">Welcome, {{user}} </a>

			{% else %}
			<a class="navbar-brand" href="{% url 'home' %}">Segmentation </a>

			{% endif %}

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  {% if user.is_authenticated %}
		      
		      <div class="collapse navbar-collapse" id="navbarNav">
		        <ul class="navbar-nav">

		          <li class="nav-item active">
		            <a class="nav-link" href="{% url 'info' %}">Information <span class="sr-only">(current)</span></a>
		          </li>

		          <li class="nav-item active">
		            <a class="nav-link" href="{% url 'detection' %}">Fraud Detection<span class="sr-only">(current)</span></a>
		          </li>

					<li class="nav-item active">
		            <a class="nav-link" href="{% url 'classifier' %}">Classifier<span class="sr-only">(current)</span></a>
		          </li>


				  
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
		          </li>

		        </ul>
		      </div>
		  
		  {% else %}
		  	<div class="collapse navbar-collapse" id="navbar-nav">
		        <ul class="navbar-nav">
		          <li class="nav-item active">
		            <a class="nav-link" href="{% url 'home' %}">Information <span class="sr-only">(current)</span></a>
		          </li>

		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
		          </li>
		          <li class="nav-item">
		            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
		          </li>
		        </ul>
		      </div>
		  {% endif %}
		</nav>


		<!-- Content -->
		<div class="container" style="margin-top: 50px;">{% block content %}{% endblock content %}</div>
		<br><br><hr><br><br>





		<button onclick="topFunction()" id="go-to-top" title="Go to top">&#8593;</button>
		<script type="text/javascript">
			//Get the button:
			go_to_top = document.getElementById("go-to-top");

			// When the user scrolls down 20px from the top of the document, show the button
			window.onscroll = function() {scrollFunction()};

			function scrollFunction() {
			  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 200) {
			    go_to_top.style.display = "block";
			  } else {
			    go_to_top.style.display = "none";
			  }
			}

			// When the user clicks on the button, scroll to the top of the document
			function topFunction() {
			  document.body.scrollTop = 0; // For Safari
			  document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
			}
		</script>
</body>
</html>

templates/classifier.html
<!DOCTYPE html>
<html>
<head>
    <title>Fraud Detection</title>
</head>
<body>
<h1>Fraud Detection</h1>
<form method="post" action="{% url 'classifier' %}">
    {% csrf_token %}


    <label for="v1">V1:</label>
    <input type="text" name="v1" id="v1" required step="0.01">
    <br>
    <label for="v2">V2:</label>
    <input type="text" name="v2" id="v2" required step="0.01">
    <br>
    <label for="v3">V3:</label>
    <input type="text" name="v3" id="v3" required step="0.01">
    <br>
    <label for="v4">V4:</label>
    <input type="text" name="v4" id="v4" required step="0.01">
    <br>
    <label for="v5">V5:</label>
    <input type="text" name="v5" id="v5" required step="0.01">
    <br>
    <label for="v6">V6:</label>
    <input type="text" name="v6" id="v6" required step="0.01">
    <br>
    <label for="v7">V7:</label>
    <input type="text" name="v7" id="v7" required step="0.01">
    <br>
    <label for="v8">V8:</label>
    <input type="text" name="v8" id="v8" required step="0.01">
    <br>
    <label for="v9">V9:</label>
    <input type="text" name="v9" id="v9" required step="0.01">
    <br>
    <label for="v10">V10:</label>
    <input type="text" name="v10" id="v10" required step="0.01">
    <br>
    <label for="v11">V11:</label>
    <input type="text" name="v11" id="v11" required step="0.01">
    <br>
    <label for="v12">V12:</label>
    <input type="text" name="v12" id="v12" required step="0.01">
    <br>
    <label for="v13">V13:</label>
    <input type="text" name="v13" id="v13" required step="0.01">
    <br>
    <label for="v14">V14:</label>
    <input type="text" name="v14" id="v14" required step="0.01">
    <br>
    <label for="v15">V15:</label>
    <input type="text" name="v15" id="v15" required step="0.01">
    <br>
    <label for="v16">V16:</label>
    <input type="text" name="v16" id="v16" required step="0.01">
    <br>
    <label for="v17">V17:</label>
    <input type="text" name="v17" id="v17" required step="0.01">
    <br>
    <label for="v18">V18:</label>
    <input type="text" name="v18" id="v18" required step="0.01">
    <br>
    <label for="v19">V19:</label>
    <input type="text" name="v19" id="v19" required step="0.01">
    <br>
    <label for="v20">V20:</label>
    <input type="text" name="v20" id="v20" required step="0.01">
    <br>
    <label for="v21">V21:</label>
    <input type="text" name="v21" id="v21" required step="0.01">
    <br>
    <label for="v22">V22:</label>
    <input type="text" name="v22" id="v22" required step="0.01">
    <br>
    <label for="v23">V23:</label>
    <input type="text" name="v23" id="v23" required step="0.01">
    <br>
    <label for="v24">V24:</label>
    <input type="text" name="v24" id="v24" required step="0.01">
    <br>
    <label for="v25">V25:</label>
    <input type="text" name="v25" id="v25" required step="0.01">
    <br>
    <label for="v26">V26:</label>
    <input type="text" name="v26" id="v26" required step="0.01">
    <br>
    <label for="v27">V27:</label>
    <input type="text" name="v27" id="v27" required step="0.01">
    <br>
    <label for="v28">V28:</label>
    <input type="text" name="v28" id="v28" required step="0.01">
    <br>

    <label for="amount">Amount:</label>
    <input type="number" name="amount" id="amount" required>
    <br>
    <input type="submit" value="Predict">
</form>
{% if prediction is not none %}
{% if prediction == 1 %}
<p>The transaction is fraudulent.</p>
{% else %}
<p>The transaction is not fraudulent.</p>
{% endif %}
{% endif %}
</body>
</html>

templates/detection.html
{% extends "base.html" %}

{% block title %}
  Credit Card
{% endblock title %}

{% block content %}
{% load static %}

<br>

<br>

<div class="row justify-content-center mt-15">
    <div class="col-md-20 text-center" text-align= "justify">

            <h1>
				credit card fraud detection using machine learning
			</h1>
    </div>
</div>

<br>
<br>



<div class="row justify-content-center mt-15">
    <div class="col-md-20 text-justify" text-align= "justify">
		It is important that credit card companies are able to recognize fraudulent credit card transactions so that customers are not charged for items that they did not purchase.
		The datasets contains transactions made by credit cards in September 2013 by european cardholders.
		This dataset presents transactions that occurred in two days, where we have 492 frauds out of 284,807 transactions. The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.
		<br><br>
		
		It contains only numerical input variables which are the result of a PCA transformation. Unfortunately, due to confidentiality issues, we cannot provide the original features and more background information about the data. Features V1, V2, … V28 are the principal components obtained with PCA, the only features which have not been transformed with PCA are 'Time' and 'Amount'. Feature 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset. The feature 'Amount' is the transaction Amount, this feature can be used for example-dependant cost-senstive learning. Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise.
		

		<br><br>
      </div>
</div>

<hr>

<h4>
	Accuracy using Machine learning model : 99.92%
</h4>


<hr>
<h4>
        Data analysis
</h4>

<div class="row justify-content-center mt-15">
	<div class="col-md-20 text-center" text-align= "justify">
			<img src="/static/img/analysis.png" class="img-responsive" style="width: 100%; float: center; " />                
			<!-- <br><br><br>          -->
	</div>
</div>

<hr>

<h4>
        Graph of Time of transaction vs Amount for Genuine and Fraud cases
</h4>

<div class="row justify-content-center mt-15">
	<div class="col-md-20 text-center" text-align= "justify">
			<br><br>
			<img src="/static/img/Fraud_or_genuine.png" class="img-responsive" style="width: 100%; float: center; " />                
			<br><br><br>         
	</div>
</div>

<hr>

<!-- <h4>
        Confusion Matrix
</h4>

<div class="row justify-content-center mt-15">
	<div class="col-md-20 text-center" text-align= "justify">
			<br><br>
			<img src="/static/img/Fraud_or_genuine.png" class="img-responsive" style="width: 100%; float: center; " />                
			<br><br><br>         
	</div>
</div> -->


<!--  -->
<!--  -->


<!--  -->







{% endblock %}



templates/fraudulent.html
<!DOCTYPE html>
<html>
<head>
	<title>Transaction Result</title>
</head>
<body>
	<h1>The transaction is fraudulent.</h1>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
	Credit Card
{% endblock title %}

{% block content %}
{% load static %}


<!DOCTYPE html>
<html>
<head>

	<link rel="stylesheet" type="text/css" href="{% static 'home_page_css .css' %}">

</head>



<div class="text-center">
			{% if not user.is_authenticated %}
				<h1> <b> credit card fraud detection using machine learning   </b> </h1>
			{% else %}
				<h1> <b> Welcome to credit card fraud detection using machine learning system, {{ user }} . ! </b> </h1>
			{% endif %}

	</div>

		<br>
		
		<div class="w3-content w3-section" style="max-width:100%">
			<img class="mySlides w3-animate-right" src="{% static 'img/c1.jpg' %}" style="height:400px;width:100%">
			<img class="mySlides w3-animate-right" src="{% static 'img/c2.jpg' %}" style="height:400px;width:100%">
			<img class="mySlides w3-animate-right" src="{% static 'img/c3.jpg' %}" style="height:400px;width:100%">
			<img class="mySlides w3-animate-right" src="{% static 'img/c4.jpg' %}" style="height:400px;width:100%">
			<img class="mySlides w3-animate-right" src="{% static 'img/c5.jpg' %}" style="height:400px;width:100%">
		  </div>
		  

				<div class="row justify-content-center ">
					<div class="text-center">
		
					 <br>
				<p style="text-align:justify;" >	
					<b>
						The credit card industry has become extremely competitive. To survive, financial institutions need to offer their credit card customers with more innovative financial services that provide a personalized customer experience beyond their banking needs. While we are witnessing this high competition that aims to provide better services to credit card holders. In this paper, we define and describe the steps that can be taken to build a behavioural-based segmentation model that differentiates credit cardholders based on their purchases data. By using DNN we get result for behavioural-based credit card users’ segmentation. 
						<br>
						<br>

						Credit card is the well-accepted manner of remission in financial field. With the rising number of users across the globe, risks on usage of credit card have also been increased, where there is danger of stealing credit card details and committing frauds. Traditionally, machine learning area has been developing algorithms that have certain assumptions on underlying distribution of data, such as data should have predetermined and fixed distribution. Real-word situations are different than this constrained model; rather applications often face problems such as unbalanced data distribution. Additionally, data picked from non-stationary environments are also frequent that results in the sudden drifts in the concepts. These issues have been separately addressed by the researcher.

					</b>			
			</div>
		</div>
	
			

		<script>
			var myIndex = 0;
			carousel();
			
			function carousel() {
			  var i;
			  var x = document.getElementsByClassName("mySlides");
			  for (i = 0; i < x.length; i++) {
				x[i].style.display = "none";  
			  }
			  myIndex++;
			  if (myIndex > x.length) {myIndex = 1}    
			  x[myIndex-1].style.display = "block";  
			  setTimeout(carousel, 2500);    
			}
		</script>
					
			
{% endblock content %}

templates/not_fraudulent.html
<!DOCTYPE html>
<html>
<head>
	<title>Transaction Result</title>
</head>
<body>
	<h1>The transaction is not fraudulent.</h1>
</body>
</html>